import { NgModule } from '@angular/core';

import {
  IonAlert,
  IonContent,
  IonCol,
  IonCardHeader,
  IonCardTitle,
  IonCardSubtitle,
  IonCard,
  IonButton,
  IonButtons,
  IonInput,
  IonLabel,
  IonItem,
  IonNote,
  IonToggle,
  IonHeader,
  IonTitle,
  IonToolbar,
  IonRippleEffect,
  IonIcon,
  IonText,
  IonRow,
  IonFooter,
  IonProgressBar,
} from '@ionic/angular/standalone';

@NgModule({
  declarations: [],
  imports: [
    IonAlert,
    IonFooter,
    IonCol,
    IonCardHeader,
    IonCardTitle,
    IonCardSubtitle,
    IonCard,
    IonButton,
    IonButtons,
    IonLabel,
    IonText,
    IonInput,
    IonItem,
    IonNote,
    IonToggle,
    IonIcon,
    IonRippleEffect,
    IonContent,
    IonHeader,
    IonTitle,
    IonRow,
    IonToolbar,
    IonProgressBar,
  ],
  exports: [
    IonAlert,
    IonFooter,
    IonCol,
    IonCardHeader,
    IonCardTitle,
    IonCardSubtitle,
    IonCard,
    IonButton,
    IonButtons,
    IonText,
    IonIcon,
    IonInput,
    IonItem,
    IonLabel,
    IonNote,
    IonToggle,
    IonRippleEffect,
    IonContent,
    IonHeader,
    IonTitle,
    IonRow,
    IonToolbar,
    IonProgressBar,
  ],
})
export class IonicBundleModule {}
